name: cognitive_complexity
description: Algorithmic Cognitive Complexity calculation library and CLI tool for Dart and Flutter.
version: 0.1.0-wip
repository: https://github.com/kevmoo/cognitive_complexity.dart

environment:
  sdk: '^3.12.0'

# Add regular dependencies here.
dependencies:
  analyzer: ^14.1.0
  args: ^2.7.0
  io: ^1.0.5
  path: ^1.9.1
  pool: ^1.5.0
  stack_trace: ^1.12.1

dev_dependencies:
  checks: ^0.3.1
  dart_flutter_team_lints: ^3.5.2
  test: ^1.31.2
  test_descriptor: ^2.0.2
  test_process: ^2.1.1
