name: cognitive_complexity
description: >-
  Algorithmic Cognitive Complexity calculation and Data-Flow analysis library
  and CLI tools for Dart and Flutter.
version: 0.2.4
repository: https://github.com/kevmoo/analytica.dart/tree/main/packages/cognitive_complexity
issue_tracker: https://github.com/kevmoo/analytica.dart/issues

topics:
  - static-analysis
  - code-quality
  - linter
  - cli
  - complexity

resolution: workspace

environment:
  sdk: '^3.12.0'

executables:
  cognitive_complexity:
  data_flow:

# Add regular dependencies here.
dependencies:
  analytica: ^0.1.1
  analyzer: '>=12.0.0 <15.0.0'
  args: ^2.7.0
  io: ^1.0.5
  path: ^1.9.1
  pool: ^1.5.0
  stack_trace: ^1.12.1

dev_dependencies:
  checks: ^0.3.1
  dart_flutter_team_lints: ^3.5.2
  test: ^1.25.0
  test_descriptor: ^2.0.2
  test_process: ^2.1.1
